CREATE TABLE `customers` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_type` text NOT NULL,
	`first_name` text,
	`last_name` text,
	`business_name` text,
	`email` text NOT NULL,
	`phone` text,
	`address_line1` text,
	`address_line2` text,
	`city` text,
	`province` text,
	`postal_code` text,
	`country` text DEFAULT 'South Africa',
	`id_number` text,
	`registration_number` text,
	`vat_number` text,
	`tax_number` text,
	`status` text DEFAULT 'active' NOT NULL,
	`notes` text,
	`created_by` text,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL
);
